name: Build and Publish NPM Package

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Tag the commit
        id: tag
        uses: mazaheriMahdi/auto-tagger-action@v0.0.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the version of Node.js to use

      - name: Install dependencies
        run: npm install

      - name: Update package version
        run: |
          # Update the version in package.json with the tag
          jq '.version = "${{ steps.tag.outputs.tag }}"' package.json > temp.json && mv temp.json package.json

      - name: Build the NPM package
        run: npm run build  # If you have a build script, adjust accordingly

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output the latest tag
        run: echo "The Latest version is ${{ steps.tag.outputs.tag }}"

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
